tidy up ci scripts (#3)
* tidy up ci scripts

* update ocean_BGC to new tag

* add 1d test case back

* Update NWA12_RT.yaml

* Update create_run_xml_from_template.bash

* Update NWA12_RT.yaml

* change name of token

* Update NWA12_RT.yaml

* Rename mom6_cobalt_1D.yaml to mom6_cobalt_1D._yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update mom6_cobalt_1D._yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update mom6_cobalt_1D._yaml

* Update Dockerfile.ci

* Update and rename mom6_cobalt_1D._yaml to mom6_cobalt_1D.yaml

* Update Dockerfile.ci

* Update mom6_cobalt_1D.yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update NWA12_RT.yaml

* Update mom6_cobalt_1D.yaml

* Update NWA12_RT.yaml

* Update mom6_cobalt_1D.yaml

* Update ContainerQuickstart.rst

* Update README.md

diff --git a/tests/Dockerfile.ci b/tests/Dockerfile.ci
--- a/tests/Dockerfile.ci
+++ b/tests/Dockerfile.ci
@@ -1,4 +1,4 @@
-From clouden90/1d_mom6_cobalt:v0.1
+From clouden90/1d_mom6_cobalt:base
 
 SHELL ["/bin/bash","-c"]
 
@@ -10,13 +10,9 @@ USER builder
 
 COPY --chown=builder:builder . /opt/MOM6_OBGC_examples
 
-WORKDIR /opt/datasets/OceanBGC_dataset
+WORKDIR /opt
 
-RUN wget https://gfdl-med.s3.amazonaws.com/OceanBGC_dataset/COBALT_2023_10_spinup_2003_subset.nc
-
-WORKDIR /opt/datasets/OM4_025.JRA.single_column
-
-RUN rm ocean_hgrid.nc; wget https://gfdl-med.s3.amazonaws.com/OceanBGC_dataset/ocean_hgrid.nc
+RUN wget https://gfdl-med.s3.amazonaws.com/OceanBGC_dataset/1d_datasets.tar.gz && tar -zxvf 1d_datasets.tar.gz && rm -rf 1d_datasets.tar.gz 
 
 WORKDIR /opt/MOM6_OBGC_examples/builds
 
@@ -29,3 +25,34 @@ RUN ln -fs /opt/datasets ./
 WORKDIR /opt/MOM6_OBGC_examples/exps/OM4.single_column.COBALT.p4
 
 RUN mpirun -np 1 /opt/MOM6_OBGC_examples/builds/build/docker-linux-gnu/ocean_ice/prod/MOM6SIS2
+
+# create ref folder
+RUN mkdir ref
+RUN cp /opt/MOM6_OBGC_examples/src/ocean_BGC/.github/ref/OM4.single_column.COBALT.p4/docker-linux-gnu/* ./ref/
+
+# check
+RUN diff -q ref/ocean.stats ./ocean.stats > /dev/null || { echo "Error: ocean.stats are different, check and update ref! Exiting now..."; exit 1; }
+
+#
+RUN ncdump ref/MOM.res.nc > org_ref.txt
+RUN ncdump RESTART/MOM.res.nc > new_ref.txt
+RUN diff -q ./org_ref.txt ./new_ref.txt > /dev/null || { echo "Error: MOM.res.nc are different, check and update ref! Exiting now..."; exit 1; }
+RUN rm org_ref.txt && rm new_ref.txt
+
+#
+RUN ncdump ref/ocean_cobalt_airsea_flux.res.nc > org_ref.txt
+RUN ncdump RESTART/ocean_cobalt_airsea_flux.res.nc > new_ref.txt
+RUN diff -q ./org_ref.txt ./new_ref.txt > /dev/null || { echo "Error: ocean_cobalt_airsea_flux.res.nc are different, check and update ref! Exiting now..."; exit 1; }
+RUN rm org_ref.txt && rm new_ref.txt
+
+# check with ref ice_cobalt.res.nc 
+RUN ncdump ref/ice_cobalt.res.nc > org_ref.txt
+RUN ncdump RESTART/ice_cobalt.res.nc > new_ref.txt
+RUN diff -q ./org_ref.txt ./new_ref.txt > /dev/null || { echo "Error: ice_cobalt.res.nc are different, check and update ref! Exiting now..."; exit 1; }
+RUN rm org_ref.txt && rm new_ref.txt
+
+# check with ref ice_model.res.nc 
+RUN ncdump ref/ice_model.res.nc > org_ref.txt
+RUN ncdump RESTART/ice_model.res.nc > new_ref.txt
+RUN diff -q ./org_ref.txt ./new_ref.txt > /dev/null || { echo "Error: ice_model.res.nc are different, check and update ref! Exiting now..."; exit 1; }
+RUN rm org_ref.txt && rm new_ref.txt
